--- 
title: 'From the mechanistic modeling of signaling pathways in cancer to the interpretation of models and their contributions: clinical applications and statistical evaluation'
author: "" # defined in _output.yml
date: "23/09/2020" # defined in _output.yml
site: bookdown::bookdown_site

documentclass: memoir # using the memoir package
classoption: a4paper,12pt,twoside,onecolumn,openright,final,oldfontcommands

lot: false # deactivating the default list of tables
lof: false # deactivating the default list of figures

link-citations: yes
bibliography: [bib/thesis.bib]
#nocite: '@ito_control_2008' # references appearing in the references section but not in text

description: "This is my PhD thesis."
---

```{r setup, include=FALSE}
#is_pdf_output = function() {
#  knitr::opts_knit$get("rmarkdown.pandoc.to") =="latex"
#}
```

```{r setupup, include=FALSE}
#is_html_output = function() {
#  knitr::opts_knit$get("rmarkdown.pandoc.to") =="html4"
#}
```

```{r setsize, include=FALSE}
#if(is_pdf_output()){
#  size.fig = "70%"
#} else {
#  size.fig = "100%"
#}


```

```{r index, echo=FALSE, results='asis', include = identical(knitr:::pandoc_to(), "html")}
#
cat("# PhD Thesis{-}
by [Jonas Béal](http://jonasbeal.github.io)

Supervised by Laurence Calzone, Aurélien Latouche and Emmanuel Barillot,

# {-}
  
  
  
  
> *Ce sont les sévères artistes*  
*Que l’aube attire à ses blancheurs,*  
*Les savants, les inventeurs tristes,*  
*Les puiseurs d’ombre, les chercheurs,*  
*Qui ramassent dans les ténèbres*  
*Les faits, les chiffres, les algèbres,*  
*Le nombre où tout est contenu,*  
*Le doute où nos calculs succombent,*  
*Et tous les morceaux noirs qui tombent*  
*Du grand fronton de l’inconnu !*  
> Victor Hugo (*Les mages*)

# Summary {-}

Beyond its genetic mechanisms, cancer can be understood as a network disease that often results from the interactions between different perturbations in a cellular regulatory network.  The dynamics of these networks and associated signaling pathways are complex and require integrated approaches. One approach is to design mechanistic models that translate the biological knowledge of networks in mathematical terms to simulate computationally the molecular features of cancers. However, these models only reflect the general mechanisms at work in cancers.  
  

This thesis proposes to define personalized mechanistic models of cancer. A generic model is first defined in a logical (or Boolean) formalism, before using omics data (mutations, RNA, proteins) from patients or cell lines in order to make the model specific to each one profile. These personalized models can then be compared with the clinical data of patients in order to validate them. The response to treatment is investigated in particular in this thesis. The explicit representation of the molecular mechanisms by these models allows to simulate the effect of different treatments according to their targets and to verify if the sensitivity of a patient to a drug is well predicted by the corresponding personalized model. An example concerning the response to BRAF inhibitors in melanomas and colorectal cancers is thus presented.  
  

The comparison of mechanistic models of cancer, those presented in this thesis and others, with clinical data also encourages a rigorous evaluation of their possible benefits in the context of medical use. The quantification and interpretation of the prognostic value of outputs of some mechanistic models is briefly presented before focusing on the particular case of models able to recommend the best treatment for each patient according to his molecular profile. A theoretical framework is defined to extend causal inference methods to the evaluation of such precision medicine algorithms. An illustration is provided using simulated data and patient derived xenografts.  
  

All the methods and applications put forward a possible path from the design of mechanistic models of cancer to their evaluation using statistical models emulating clinical trials. As such, this thesis provides one framework for the implementation of precision medicine in oncology.  
  
**Keywords**: Modeling, Cancer, Mechanistic model, Biostatistics, Causal inference, Precision medicine.

# Resumé {-}

Au delà de ses mécanismes génétiques, le cancer peut être compris comme une maladie de réseaux qui résulte souvent de l’interaction entre différentes perturbations dans un réseau de régulation cellulaire.  La dynamique de ces réseaux et des voies de signalisation associées est complexe et requiert des approches intégrées. Une d’entre elles est la conception de modèles dits mécanistiques qui traduisent mathématiquement la connaissance biologique des réseaux afin de pouvoir simuler le fonctionnement moléculaire des cancers informatiquement. Ces modèles ne traduisent cependant que les mécanismes généraux à l’oeuvre dans certains cancers en particulier.  
  

Cette thèse propose en premier lieu de définir des modèles mécanistiques personnalisés de cancer. Un modèle générique est  d’abord défini dans un formalisme logique (ou Booléen), avant d’utiliser les données omiques (mutations, ARN, protéines) de patients ou de lignées cellulaires afin de rendre le modèle spécifique à chacun. Ces modèles personnalisés peuvent ensuite être confrontés aux données cliniques de patients pour vérifier leur validité. Le cas de la réponse clinique aux traitements est exploré en particulier dans ce travail. La représentation explicite des mécanismes moléculaires par ces modèles permet en effet de simuler l’effet de différents traitements suivant leur mode d’action et de vérifier si la sensibilité d’un patient à un traitement est bien prédite par le modèle personnalisé correspondant. Un exemple concernant la réponse aux inhibiteurs de BRAF dans les mélanomes et cancers colorectaux est ainsi proposé.  
  

La confrontation des modèles mécanistiques de cancer, ceux présentés dans cette thèse et d’autres, aux données cliniques incite par ailleurs à évaluer rigoureusement leurs éventuels bénéfices dans la cadre d’une utilisation médicale. La quantification et l’interprétation de la valeur pronostique des biomarqueurs issus de certains modèles méchanistiques est brièvement présentée avant de se focaliser sur le cas particulier des modèles capables de sélectionner le meilleur traitement pour chaque patient en fonction des ses caractéristiques moléculaires. Un cadre théorique est proposé pour étendre les méthodes d’inférence causale à l’évaluation de tels algorithmes de médecine de précision. Une illustration est fournie à l’aide de données simulées et de xénogreffes dérivées de  patients.  
  

L’ensemble des méthodes et applications décrites tracent donc un chemin, de la conception de modèles mécanistiques de cancer à leur évaluation grâce à des modèles statistiques émulant des essais cliniques, proposant ainsi un cadre pour la mise en oeuvre de la médecine de précision en oncologie.  
  

**Mots-clés**: Modélisation, Cancer, Modèle mécanistique, Biostatistiques, Inférence causale, Médecine de précision.

# Acknowledgements {-}

On ne se lance pas une thèse dans le seul but d’en écrire les remerciements. C’est peut être un tort tant l’occasion est belle d’en profiter pour exprimer sa gratitude à tous ceux qui la méritent sans que l’on pense toujours à le leur dire. Je vais donc essayer de remercier tous ceux qui occupent mon esprit à l’heure où j’écris ces lignes, d’un bout à l’autre du spectre, de ceux sans qui cette thèse n’aurait pas été la même à ceux sans qui je serais bien différent.  
  

Merci tout d’abord aux membres du jury, Denis Thieffry, Émilie Lanoy, et en particulier aux rapporteurs Adeline Leclerq-Samson et Lodewyk Wessels, d’avoir accepté d’évaluer ce travail, contribuant ainsi à le rendre plus enrichissant pour moi. Merci également aux membres de mes comités de suivi de thèses Benno Schwikowski, Mélanie Prague et Xavier Paoletti pour leur regard extérieur et leurs remarques pertinentes et constructives.  
  

Mes remerciements suivants, à la fois professionnels et personnels vont à Laurence, Aurélien et Emmanuel pour avoir supervisé cette thèse en m’orientant sans me diriger, dans un juste équilibre d’encadrement et de liberté, chacun suivant ses spécificités. Merci en particulier à Laurence pour son inépuisable bienveillance, prodiguée avec générosité. Merci à Aurélien pour sa disponibilité et sa positivité, mot piégé s’il en est. Et enfin merci à Emmanuel pour sa capacité à prendre du recul.  
  

Merci ensuite à tous les collègues de l’équipe de biologie des systèmes, présents ou passés, particulièrement ceux avec lesquels j’ai pu collaborer directement. Merci à Arnau pour m’avoir inoculé son souci excessif de certains détails, à Vincent pour m’avoir enseigné certaines bonnes pratiques, à Pauline pour m’avoir accueilli à l’Institut et à Lorenzo pour m’avoir supporté. Merci plus largement à tous les membres de l’équipe qui ont fait de cette thèse une période d’échanges, scientifiques ou non: Nicolas, Mihaly, Cristobal, Andrei, Urczula, Céline, Laura, Loredana, Jane, Om, Marianyela, Christine, Maria, Inna. Mention spéciale à mes collègues de bureau successifs Loïc et Jonathan pour leur humour bienvenu et pour avoir toléré le mien. Merci de la même manière aux collègues de de l’équipe STAMPM, tout spécialement à Bassirou et Alessandra pour m’avoir accueilli dans leur bureau mouvant de Saint Cloud, mais aussi Christophe et Xavier (à nouveau) pour leur écoute et leurs conseils. Merci aux autres membres de l’U900, avec une pensée particulière pour Caroline et Kati dont le sens de l’organisation a contribué à me faciliter la vie.  
  

Merci également à tous ces collègues inconnus qui partagent librement connaissances, tutoriels, code informatique ou modèles typographiques. Ils forment une communauté virtuelle à l’impact bien réel.  
  

Merci aussi à ceux qui ont contribué à orienter mon parcours au fil des années, de Polytechnique à la biologie computationnelle. Je pense notamment à François et Fred chez Novadiscovery ainsi qu’à Vassily et Misko à l’EPFL.  
  

De manière toujours plus personnelle, je me dois aussi de remercier tous les amis qui ont fait de ces trois années un voyage agréable. Au sein de l’Institut tout d’abord, pour quelques repas avec Élise et Anne, au Collège des Ingénieurs, pour des discussions intellectuellement variées et rafraichissantes.  Merci ensuite à tous ces amis, connus à Saint-Étienne, Lyon, Palaiseau, Paris ou Lausanne, que se reconnaitront sans qu’il soit nécessaire de tous les nommer exhaustivement. Mention spéciale à Guillaume, Laurent, Reda, Michaël, Pierre, Etienne, Florian et Amélie pour m’avoir aidé ou réjoui plus souvent qu’à leur tour.  
  

Une grande partie de la gratitude restante à ce stade revient à ma famille pour son soutien sans faille. Merci à mes parents, frère, soeur et grand-mère pour m’avoir accompagné tout au long de mes études de leur curiosité et de leur fierté, autant de vent dans mes voiles sans lequel je n’aurais pas tant avancé. Merci tout spécialement à mes parents, je dois à votre tranquille mais tenace confiance de n’avoir jamais douté de ma capacité à choisir ma voie et à la tracer avec succès.  
  

Enfin merci à Honorine pour tout le reste, c’est à dire pour l’essentiel. Si \"*on ne possède d’un être que ce qu’on change en lui*\"^[André Malraux, *La condition humaine*], ne doute jamais qu’une large portion de ce travail t'appartient. Son auteur quant à lui ne s’appartient déjà plus tout à fait…

# Preface {-}

The present thesis is structured in three parts, each subdivided into three chapters. Since the whole thesis is about cancer modeling, the first part aims at defining the type of model to be referred to, and in particular models that will be called mechanistic, as well as the object of the modeling, *i.e.*, the molecular networks involved in cancer. So the first part answers the question: **what is a cancer model and what is its purpose?**  
  

The second part will be devoted to the methods developed during this thesis to transform qualitative models of molecular networks, known as logical models, into personalized models that can be interpreted clinically. In short, **how can a mathematical representation of biological knowledge be transformed into a tool that contributes to the understanding of the clinical manifestations of cancer?**  
  

Finally, the third and last part will look at how the clinical relevance of all the above-mentioned models can be rigorously evaluated, both in their ability to predict the evolution of the disease and in their ability to recommend the most appropriate treatments for each patient. **How to quantify and interpret the value of the clinical information delivered by these models?**  
  

Moreover, this thesis also exists in an online version that allows to take advantage of the interactivity of some graphs and applications: https://jonasbeal.github.io/files/PhdThesis/.

<div class='summarybox'>

#### Scientific content {-}

Except for the first part, essentially introductory and based on scientific literature, the different chapters are based on original scientific work done during this thesis (2017-2020) and mentioned at the beginning of each chapter in a box similar to the this one.  
  
The main articles behind this thesis are indicated below with one published article and two pre-prints currently under review: 

* Béal, Jonas, Arnau Montagud, Pauline Traynard, Emmanuel Barillot, and Laurence Calzone. \"Personalization of logical models with multi-omics data allows clinical stratification of patients.\" Frontiers in physiology 9 (2019): 1965. [Link](https://www.frontiersin.org/articles/10.3389/fphys.2018.01965/full).
* Béal, Jonas, Lorenzo Pantolini, Vincent Noël, Emmanuel Barillot, and Laurence Calzone. \"Personalized logical models to investigate cancer response to BRAF treatments in melanomas and colorectal cancers.\" bioRxiv (2020). [Link](https://www.biorxiv.org/content/10.1101/2020.05.27.119016v2).
* Béal, Jonas, and Aurélien Latouche. \"Causal inference with multiple versions of treatment and application to personalized medicine.\" arXiv preprint arXiv:2005.12427 (2020). [Link](https://arxiv.org/abs/2005.12427).  
  
These three articles were described or completed in oral presentations, respectively in International Conference of Systems Biology 2018, conference on Intelligent Systems for Molecular Biology (ISMB/ECCB 2019, [Video](https://www.youtube.com/watch?v=6EMBycoR0Ow)) and conference of International Society of Clincial Biostatistics (ISCB41, coming in August 2020).

</div>

")

````

